### ISSUE TITLE
Review of "names(), rbind() and cbind()"

### ISSUE THREAD

**Issue by michael-chong** [RohanAlexander/DoSStoolkit#4]
- [x] I think it might be worth mentioning in passing that renaming columns is maybe better done with `rename()` since it's a bit more foolproof than indexing
- [x] Perhaps also bring up `colnames()` as a way to access column names
- [x] Is it worth adding that `rbind()` and `cbind()` can be used to combine matrices as well?
- [ ] Is it worth bringing up differences with `bind_cols()` and `bind_rows()`?

**Comment by RohanAlexander** [comment]
Same with this one please @imehrlich

**Comment by imehrlich** [comment]
@RohanAlexander I think Michael brings up an interesting point about `bind_rows()/bind_cols()`? 

From what I understand these are the dplyr versions of `rbind()/cbind()`, and `bind_rows()` is actually a bit more robust since it doesn't require the input data frames to have the same number of columns. Given that most of the other lessons focus on the tidyverse functions, do we want to rework this to focus on `bind_rows()/bind_cols()` instead of `rbind()/cbind()`, or should we just mention the tidy functions in passing?

**Comment by RohanAlexander** [comment]
Thanks for this @imehrlich.
We need to get this 0.2.0 release live, so I've just added a paragraph along the lines of your comment into the content.
