### ISSUE TITLE
Review of "Simulating regression datasets"

### ISSUE THREAD

**Issue by michael-chong** [RohanAlexander/DoSStoolkit#6]
There's a lot of redundancy between this and the "set.seed()..." section. Not sure how this should be handled.

- [x] The text describing how `evaluations` is generated has a typo: _Using `runif()` to take 50 values with a minimum of **3** and a maximum of **4**
- [x] Maybe the example would be a little bit more intuitive if there was a true regression relationship? (So that the reader can see that the purpose of simulating the dataset could be to recover some slope parameter) This is done in the Next Steps section, but I think it could just be included in the main text.
- [x] In Exercise 2, "STA130" is listed twice in the text
- [x] Although I like this question structure, the scenario in Exercise 2 could be a little clearer, (i.e. what's the interpretation of the vector produced by `sample()`). I'm also not sure what "above data" refers to -- is there something that isn't showing up correctly?

**Comment by mwalaa** [comment]
Thanks Michael!

**1.** I've made this fix! (But this example will probably be removed since I'm updating them)
**2.** That makes more sense, thank you! I changed the example so that the Y variable depends on the X variable. I also moved the example you wrote from Next Steps over to the Overview section. The data set I made is now representing course grades average (X) and course evaluations average (Y) with a positive relationship. Do you think this is a more suitable example?
**3.** I've made this fix as well! (But this example will also probably be removed since I'm updating them)
**4.** I changed it to a simpler example for the sample() function with a jar full of red, blue, and yellow balls. Do you think this is a better example, or maybe too familiar of an example?

I agree there's a lot of overlap between this and the previous section, do you think it's better to omit the parts describing what the individual functions do since that is covered in the previous section? Maybe the arguments as well?

Thank you!
Mariam

**Comment by michael-chong** [comment]
I think all of these have either been addressed or no longer apply. Thanks @mwalaa!
